use_frameworks!

target 'GradleXcodeSubprojectExample_Example' do
  pod 'GradleXcodeSubprojectExample', :path => '../'

  target 'GradleXcodeSubprojectExample_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
